return {}
-- vim.keymap.set ("n", "<C-e>", ":NvimTreeToggle<CR>", {silent = true, noremap = true})
-- return
-- {
--   "nvim-tree/nvim-tree.lua",
--   version = "*",
--   lazy = false,
--   dependencies = {
--     "nvim-tree/nvim-web-devicons",
--   },
--   config = function()
--     require("nvim-tree").setup({
--       sort = {
--         sorter = "case_sensitive",
--       },
--       view = {
--         width = 30,
--       },
--       renderer = {
--         group_empty = true,
--       },
--       filters = {
--         dotfiles = true,
--       },
--       on_attach = function (bufnr)
--         vim.keymap.set ("n", "<C-e>", ":NvimTreeToggle<CR>", {silent = true, noremap = true})
--       end
--     })
--   end,
-- }
