require("custom.remap")
require("custom")
require("custom.set")
require("custom.globals")
require("custom.autocommands")
require("custom.highlight")

local plugins = "custom.plugins."

-- colorschemes
Spec(plugins .. "colorscheme.rose-pine")

-- LSP related
Spec(plugins .. "lsp.conform")
Spec(plugins .. "lsp.lspconfig")
Spec(plugins .. "lsp.mason")
Spec(plugins .. "lsp.navbuddy")
Spec(plugins .. "lsp.nvim-lint")
Spec(plugins .. "lsp.treesiter")

-- General
Spec(plugins .. "alpha")
Spec(plugins .. "autopairs")
Spec(plugins .. "barbecue")
Spec(plugins .. "btterm")
Spec(plugins .. "chatgpt")
Spec(plugins .. "cmp")
Spec(plugins .. "colorizer")
Spec(plugins .. "commentary")
Spec(plugins .. "copilot")
Spec(plugins .. "discord")
Spec(plugins .. "dressing")
Spec(plugins .. "flybuf")
Spec(plugins .. "focus")
Spec(plugins .. "hawtkeys")
Spec(plugins .. "hop")
Spec(plugins .. "illuminate")
Spec(plugins .. "indentlines")
Spec(plugins .. "lazygit")
Spec(plugins .. "lualine")
Spec(plugins .. "luasnip")
Spec(plugins .. "mini")
-- Spec(plugins .. "netrw")
Spec(plugins .. "rainbow-delimiters")
Spec(plugins .. "surround")
Spec(plugins .. "telescope")
Spec(plugins .. "tmux")
Spec(plugins .. "trouble")
Spec(plugins .. "ufo")
Spec(plugins .. "vim-go")
Spec(plugins .. "vim-kitty")
Spec(plugins .. "vim-kubectl")

-- Loads all with alpha
require("custom.lazy")
