require("custom.remap")
require("custom")
require("custom.set")
require("custom.globals")
require("custom.lazy")
require("custom.colorscheme")
require("custom.autocommands")
require("custom.highlight")
